include $(LVGL_DIR)/lv_ex_arc/lv_ex_arc_1.c
include $(LVGL_DIR)/lv_ex_bar/lv_ex_bar_1.c
include $(LVGL_DIR)/lv_ex_btn/lv_ex_btn_1.c
include $(LVGL_DIR)/lv_ex_btnm/lv_ex_btnm_1.c
include $(LVGL_DIR)/lv_ex_cb/lv_ex_cb_1.c
include $(LVGL_DIR)/lv_ex_chart/lv_ex_chart_1.c
include $(LVGL_DIR)/lv_ex_canvas/lv_ex_canvas_1.c
include $(LVGL_DIR)/lv_ex_cont/lv_ex_cont_1.c
include $(LVGL_DIR)/lv_ex_ddlist/lv_ex_ddlist_1.c
include $(LVGL_DIR)/lv_ex_gauge/lv_ex_gauge_1.c
include $(LVGL_DIR)/lv_ex_img/lv_ex_img_1.c
include $(LVGL_DIR)/lv_ex_imgbtn/lv_ex_imgbtn_1.c
include $(LVGL_DIR)/lv_ex_kb/lv_ex_kb_1.c
include $(LVGL_DIR)/lv_ex_label/lv_ex_label_1.c
include $(LVGL_DIR)/lv_ex_led/lv_ex_led_1.c
include $(LVGL_DIR)/lv_ex_line/lv_ex_line_1.c
include $(LVGL_DIR)/lv_ex_list/lv_ex_list_1.c
include $(LVGL_DIR)/lv_ex_lmeter/lv_ex_lmeter_1.c
include $(LVGL_DIR)/lv_ex_mbox/lv_ex_mbox_1.c
include $(LVGL_DIR)/lv_ex_page/lv_ex_page_1.c
include $(LVGL_DIR)/lv_ex_preload/lv_ex_preload_1.c
include $(LVGL_DIR)/lv_ex_roller/lv_ex_roller_1.c
include $(LVGL_DIR)/lv_ex_slider/lv_ex_slider_1.c
include $(LVGL_DIR)/lv_ex_sw/lv_ex_sw_1.c
include $(LVGL_DIR)/lv_ex_ta/lv_ex_ta_1.c
include $(LVGL_DIR)/lv_ex_tabview/lv_ex_tabview_1.c
include $(LVGL_DIR)/lv_ex_table/lv_ex_table_1.c
include $(LVGL_DIR)/lv_ex_tileview/lv_ex_tileview_1.c
include $(LVGL_DIR)/lv_ex_win/lv_ex_win_1.c

