OBJFILES += \
$(LV_EXAMPLES_PATH)/lv_tests/lv_test_group/lv_test_group.o \
$(LV_EXAMPLES_PATH)/lv_tests/lv_test_objx/lv_test_kb/lv_test_kb.o \
$(LV_EXAMPLES_PATH)/lv_tests/lv_test_objx/lv_test_bar/lv_test_bar.o \
$(LV_EXAMPLES_PATH)/lv_tests/lv_test_objx/lv_test_gauge/lv_test_gauge.o \
$(LV_EXAMPLES_PATH)/lv_tests/lv_test_objx/lv_test_btn/lv_test_btn.o \
$(LV_EXAMPLES_PATH)/lv_tests/lv_test_objx/lv_test_sw/lv_test_sw.o \
$(LV_EXAMPLES_PATH)/lv_tests/lv_test_objx/lv_test_chart/lv_test_chart.o \
$(LV_EXAMPLES_PATH)/lv_tests/lv_test_objx/lv_test_mbox/lv_test_mbox.o \
$(LV_EXAMPLES_PATH)/lv_tests/lv_test_objx/lv_test_img/lv_test_img.o \
$(LV_EXAMPLES_PATH)/lv_tests/lv_test_objx/lv_test_img/img_flower_icon.o \
$(LV_EXAMPLES_PATH)/lv_tests/lv_test_objx/lv_test_ta/lv_test_ta.o \
$(LV_EXAMPLES_PATH)/lv_tests/lv_test_objx/lv_test_btnm/lv_test_btnm.o \
$(LV_EXAMPLES_PATH)/lv_tests/lv_test_objx/lv_test_line/lv_test_line.o \
$(LV_EXAMPLES_PATH)/lv_tests/lv_test_objx/lv_test_tabview/lv_test_tabview.o \
$(LV_EXAMPLES_PATH)/lv_tests/lv_test_objx/lv_test_list/lv_test_list.o \
$(LV_EXAMPLES_PATH)/lv_tests/lv_test_objx/lv_test_win/lv_test_win.o \
$(LV_EXAMPLES_PATH)/lv_tests/lv_test_objx/lv_test_led/lv_test_led.o \
$(LV_EXAMPLES_PATH)/lv_tests/lv_test_objx/lv_test_cont/lv_test_cont.o \
$(LV_EXAMPLES_PATH)/lv_tests/lv_test_objx/lv_test_cb/lv_test_cb.o \
$(LV_EXAMPLES_PATH)/lv_tests/lv_test_objx/lv_test_slider/lv_test_slider.o \
$(LV_EXAMPLES_PATH)/lv_tests/lv_test_objx/lv_test_page/lv_test_page.o \
$(LV_EXAMPLES_PATH)/lv_tests/lv_test_objx/lv_test_label/lv_test_label.o \
$(LV_EXAMPLES_PATH)/lv_tests/lv_test_objx/lv_test_roller/lv_test_roller.o \
$(LV_EXAMPLES_PATH)/lv_tests/lv_test_objx/lv_test_ddlist/lv_test_ddlist.o \
$(LV_EXAMPLES_PATH)/lv_tests/lv_test_objx/lv_test_lmeter/lv_test_lmeter.o \
$(LV_EXAMPLES_PATH)/lv_tests/lv_test_theme/lv_test_theme.o \
$(LV_EXAMPLES_PATH)/lv_tests/lv_test_obj/lv_test_obj.o \
$(LV_EXAMPLES_PATH)/lv_apps/terminal/terminal.o \
$(LV_EXAMPLES_PATH)/lv_apps/benchmark/benchmark.o \
$(LV_EXAMPLES_PATH)/lv_apps/sysmon/sysmon.o \
$(LV_EXAMPLES_PATH)/lv_apps/files/files.o \
$(LV_EXAMPLES_PATH)/lv_apps/demo/demo.o \
$(LV_EXAMPLES_PATH)/lv_apps/demo/img_bubble_pattern.o \
$(LV_EXAMPLES_PATH)/lv_tutorial/10_keyboard/ex_keyboard.o \
$(LV_EXAMPLES_PATH)/lv_tutorial/8_animations/lv_ex_animations.o \
$(LV_EXAMPLES_PATH)/lv_tutorial/9_responsive/lv_ex_responsive.o \
$(LV_EXAMPLES_PATH)/lv_tutorial/0_porting/ex_porting.o \
$(LV_EXAMPLES_PATH)/lv_tutorial/3_styles/ex_styles.o \
$(LV_EXAMPLES_PATH)/lv_tutorial/5_antialiasing/ex_antialiasing.o \
$(LV_EXAMPLES_PATH)/lv_tutorial/2_objects/ex_objects.o \
$(LV_EXAMPLES_PATH)/lv_tutorial/1_hello_world/ex_hello_world.o \
