include $(LVGL_DIR)/arc/lv_ex_arc_1.c
include $(LVGL_DIR)/bar/lv_ex_bar_1.c
include $(LVGL_DIR)/btn/lv_ex_btn_1.c
include $(LVGL_DIR)/btnm/lv_ex_btnm_1.c
include $(LVGL_DIR)/cb/lv_ex_cb_1.c
include $(LVGL_DIR)/chart/lv_ex_chart_1.c
include $(LVGL_DIR)/canvas/lv_ex_canvas_1.c
include $(LVGL_DIR)/cont/lv_ex_cont_1.c
include $(LVGL_DIR)/ddlist/lv_ex_ddlist_1.c
include $(LVGL_DIR)/gauge/lv_ex_gauge_1.c
include $(LVGL_DIR)/img/lv_ex_img_1.c
include $(LVGL_DIR)/imgbtn/lv_ex_imgbtn_1.c
include $(LVGL_DIR)/kb/lv_ex_kb_1.c
include $(LVGL_DIR)/label/lv_ex_label_1.c
include $(LVGL_DIR)/led/lv_ex_led_1.c
include $(LVGL_DIR)/line/lv_ex_line_1.c
include $(LVGL_DIR)/list/lv_ex_list_1.c
include $(LVGL_DIR)/lmeter/lv_ex_lmeter_1.c
include $(LVGL_DIR)/mbox/lv_ex_mbox_1.c
include $(LVGL_DIR)/page/lv_ex_page_1.c
include $(LVGL_DIR)/preload/lv_ex_preload_1.c
include $(LVGL_DIR)/roller/lv_ex_roller_1.c
include $(LVGL_DIR)/slider/lv_ex_slider_1.c
include $(LVGL_DIR)/sw/lv_ex_sw_1.c
include $(LVGL_DIR)/ta/lv_ex_ta_1.c
include $(LVGL_DIR)/tabview/lv_ex_tabview_1.c
include $(LVGL_DIR)/table/lv_ex_table_1.c
include $(LVGL_DIR)/tileview/lv_ex_tileview_1.c
include $(LVGL_DIR)/win/lv_ex_win_1.c

